name: Test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Run tests
        run: |
          python ./feature.py
          python ./testgit.py
          python ./login.py

      - name: commit and push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update apply"
          commit_user_name: BadRequest0404 [GitHub Actions]
          commit_user_email: lalocga@gmail.com
          commit_author: BadRequest0404 [GitHub Actions] <lalocga@gmail.com>


